apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: notest
  janus-idp.io/tekton: notest
  backstage.io/kubernetes-id: notest
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: notest
resources:
- deployment.yaml
- route.yaml
- service.yaml
